<?php
require_once PLUGIN_BASE_PATH . '/classes/galleryzip.php';

/**
 * Test class for GalleryZip.
 * Generated by PHPUnit on 2013-05-16 at 10:06:41.
 * @covers GalleryZip\GalleryZip
 */
class GalleryZipTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GalleryZip
     */
    protected $object;

    /**
     * point this id to an existing post with a gallery
     * @var integer
     */
    protected $post_id = 555;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    	global $post;

        $this->object = GalleryZip\GalleryZip::get_instance();

        $post = get_post( $this->post_id );

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    /**
     * @covers GalleryZip\GalleryZip::get_instance()
     */
    public function testGet_instance() {
    	$this->assertNotNull( $this->object );
    }

    /**
     * @covers GalleryZip\GalleryZip::gallery_zip_shortcode().
     */
    public function testGallery_zip_shortcode() {
    	$output = $this->object->gallery_zip_shortcode( array( 'ids' => '127,128,129' ) );
    	$this->assertNotEmpty( $output );
    }
}

