<?php
require_once PLUGIN_BASE_PATH . '/classes/galleryzip.php';

/**
 * Test class for GalleryZip.
 * Generated by PHPUnit on 2013-05-16 at 10:06:41.
 * @covers GalleryZip\GalleryZip
 */
class GalleryZipTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var GalleryZip
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = GalleryZip\GalleryZip::get_instance();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    /**
     * @covers GalleryZip\GalleryZip::get_instance()
     */
    public function testGet_instance() {
    	$this->assertNotNull( $this->object );
    }

    /**
     * @covers GalleryZip\GalleryZip::gallery_zip_shortcode().
     */
    public function testGallery_zip_shortcode() {
    	$this->markTestSkipped( 'Need mocking!' );
    	$output = $this->object->gallery_zip_shortcode( array( 'ids' => '127,128,129' ) );
    	$this->assertNotEmpty( $output );
    }

    /**
     * @todo Implement testSave_in_session().
     */
    public function testSave_in_session() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_images_ajax_callback().
     */
    public function testGet_images_ajax_callback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}

