<?php
require_once PHPUnitClassesPath . 'zipper.php';

/**
 * Test class for GalleryZip.
 * Generated by PHPUnit on 2013-05-16 at 10:06:41.
 */
class ZipperTest extends //WP_UnitTestCase
PHPUnit_Framework_TestCase
{
    /**
     * @var Zipper
     */
    protected $zipper;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        $this->zipper = new Zipper();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    public function tearDown() {
    }

    /**
     * @covers zip_dir()
     */
    public function testZip_dir() {
    	$source = 'some/path/badDir';
    	$target = 'foo';

    	$result = $this->zipper->zip_dir( $target, $source );

    	$this->assertNotEmpty( $this->zipper->errors );
    	$this->assertFalse( $result );
    }

}
